config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products, only: %i[index show edit update destroy new create] do
    resources :orders, only: %i[new create]
  end
  resources :orders, only: %i[index show]
  root to: 'pages#home'
  resource :profiles
  get "/profile/:id", to: "pages#profile"
  # get "/my_profile", to: "pages#my_profile", as: "my_profile"
  # get "/my_profile/edit", to: "pages#edit"
  # post "/my_profile/edit", to: "pages#edit"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  validates :estimated_delivery, inclusion: 0..15
  belongs_to :user
  has_many :orders, dependent: :destroy
  has_one_attached :photo
  validates :estimated_delivery, inclusion: 0..15

  include PgSearch::Model
  pg_search_scope :search_by_name_and_description,
    against: [ :name, :description ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  has_many :orders
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    #devise_parameter_sanitizer.permit(:account_update, keys: [:name, :address, :available, :estimated_reopen])
  end

end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
  end

  def create
  end

  def index
  end

  def show
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :delete]

  def index
    @orders = current_user.orders
  end

  def show
    @orders = Order.where(user_id: current_user)
  end

  def new
    @product = Product.find(params[:product_id])
    @order = Order.new
  end

  def create
    @product = Product.find(params[:product_id])
    @order = Order.new
    @order.user = current_user
    @order.product = @product
    if @order.save
      redirect_to products_path
    else
      render :new
    end
  end

  def delete
    @order.destroy
  end

  private

  def set_order
    @order = Order.find(user_id: current_user.id, product_id: params[:id])
  end

  def order_params
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end

  def profile
    @user = User.find(params[:id])
  end

  def edit
    @user = current_user
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    if params[:query]
      @products = Product.search_by_name_and_description(params[:query])
    else
      @products = Product.all
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    @product.save

    redirect_to profiles_path
  end

  def show
    @order = Order.new
  end

  def edit
  end

  def update
    @product.update(product_params)
    redirect_to profiles_path
  end

  def destroy
    @product.destroy
    redirect_to profiles_path
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, :estimated_delivery, :description, :photo)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show

  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to profiles_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :address, :available, :photo)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def pluralize(word, number)
    number != 1 ? "#{number} #{word}s" : "#{number} #{word}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Patissehub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/orders/_new.html.erb
<h4 class="mb-3 fw-bold"><%= product.name %></h4>
<h5>Patisserie: <b><%= product.user.name %></b></h5>
<h5>Endereço: <b><%= product.user.address %></b></h5>
<h5>Valor: <b><%= number_to_currency(@product.price, delimiter: "", unit: "R$") %></b></h5>
<h5>Entrega estimada: <b><%= (Date.today + product.estimated_delivery).strftime("%e, %b %Y") %></b></h5>

<div class="row justify-content-end border-top pt-3">
  <div class="col-6 text-end">
    <%= simple_form_for ([product, @order]) do |f| %>
      <%= f.submit 'Finalizar pedido!', class:'btn btn-primary fs-5' %>
    <% end %>
  </div>
</div>

app/views/orders/create.html.erb
<h1>Order#create</h1>
<p>Find me in app/views/order/create.html.erb</p>

app/views/orders/index.html.erb
<%= render 'shared/bootstrap_container' do %>
  <div class="col">
    <% @orders.reverse.each do |order| %>
      <div class="card mb-3">
        <h4 class="card-header"><%= order.created_at.strftime("%e, %b %Y - %R") %> </h4>
        <div class="card-body">
          <h4 class="card-title"><%= link_to order.product.name, product_path(order.product) %></h4>
          <h5>Loja: <%= order.product.user.name %></h5>
          <h5>Valor: <b><%= number_to_currency(order.product.price, delimiter: "", unit: "R$") %></b></h5>
          <h5>Entrega estimada: <b><%= (order.created_at + order.product.estimated_delivery.days).strftime("%e, %b %Y") %></b></h5>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/orders/show.html.erb
<h1>Order#show</h1>
<p>Find me in app/views/order/show.html.erb</p>

app/views/pages/edit.html.erb
<h1>Editar Usuario</h1>
<%= simple_form_for(my_profile_edit_url) do |f| %>
  <%= f.input :name %>
  <%= f.submit 'Salvar', class:'btn btn-primary mt-2' %>
<% end %>

app/views/pages/home.html.erb
<div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://2497.cdn.simplo7.net/static/2497/sku/tecido-tricoline-estampado-tricoline-bolinhas-micro-p1002-603-laranja--p-1534515116428.jpg)">
  PatisseHub
</div>

<div class="container">
  <div class="row justify-content-center mt-5" >
    <div class="col-lg-8">
      <form action="/products" accept-charset="UTF-8" method="get">
        <div class="justify-content-center input-group ">
            <div class="col-12">
              <input type="text" name="query" id="query" class="form-control col-12 mb-3" placeholder="O que vai adoçar seu dia hoje?">
            </div>
            <div class="col-12 d-flex justify-content-center">
              <input type="submit" name="commit" value="Buscar" class="btn btn-primary fs-5" data-disable-with="Search">
            </div>
        </div>
      </form>
    </div>
  </div>
</div>

app/views/pages/my_profile.html.erb
<%= render 'shared/bootstrap_container' do%>
  <div class="row">
    <div class="col-1 me-4 me-md-1">
      <img class="avatar-large" alt="avatar-large" src="https://kitt.lewagon.com/placeholder/users/arthur-littm" />
    </div>
    <div class="col-10">
      <div class="card-profile">
        <div class="card-profile-infos">
          <h3><%= current_user.name %></h3>
          <p><%= current_user.email %></p>
          <%= link_to my_profile_edit_url do %>
          <i class="far fa-edit fs-4"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <h3 class='text-center pt-4 my-2'>Seu cardápio</h3>
  <%= link_to 'Cadastrar Novo Produto', new_product_path %>
  <% current_user.products.each do |product| %>
    <div class="card my-3 align-items-stretch">
      <div class="card-header row align-items-center">
        <div class="col-10 align-self-center fs-4">
          <%= product.name %>
        </div>
        <div class="col-2 text-end">
          <%= link_to edit_product_path(product) do %>
          <i class="far fa-edit fs-4"></i>
          <% end %>
          <%= link_to product_path(product), method: :delete do %>
            <i class="fa-solid fa-trash text-danger fs-4"></i>
          <% end %>
        </div>
      </div>
      <div class="m-3">
        <h5 class="card-title">
          Valor: R$<%= product.price %>
        </h5>
        <h5 class="card-title">
          Tempo de produção: <%= pluralize('dia' , product.estimated_delivery) %>
        </h5>
        <p class='card-text'><%= product.description %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/pages/profile.html.erb
<%= render 'shared/bootstrap_container' do %>
  <% if @user.products.size > 0 %>
    <h3><%= @user.name %></h3>
    <h4 class='text-secondary'><%= @user.address %></h4>
    <h4 class='text-center'>Cardápio</h4>
    <% @user.products.each do |product| %>
      <div class="col-md-6 col-xl-4 my-3">
        <div class="card">
          <h5 class="card-header"><%=product.name%></h5>
          <%= cl_image_tag product.photo.key, class: 'card-img-top card-image', crop: "fill" %>
          <div class="card-body">
            <p class="card-text card-description"><%=product.description%></p>
            <div class="row justify-content-between align-items-center">
              <div class="col-5 align-self-center">
                <span class="align-self-center fs-5">R$<%= '%.2f' % product.price%></span>
              </div>
              <div class="col-7 text-end align-items-center">
                <span class="<%='text-primary' if product.estimated_delivery == 0 %>">
                  <%if product.estimated_delivery == 0%>
                    Pronta entrega
                  <% elsif product.estimated_delivery == 1%>
                    Entrega amanhã
                  <% else %>
                    Entrega em <%= product.estimated_delivery %> dias
                  <% end %>
                </span>
              </div>
              <div class="col-12 text-end align-items-center">
                Distância: <%= current_user.distance_to(product.user).round(0)%> km
              </div>
              <div class="col-12 mt-2 text-center">
                <%= link_to product_path(product) do %>
                  <button class="btn btn-primary w-100 fs-5" >Mais detalhes</button>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <h2>Este usuário não tem </h2>
  <% end %>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(product) do |f| %>
  <%= f.input :name %>
  <%= f.input :price, in: 1.0..20.0, step: 0.5 %>
  <%= f.input :description %>
  <%= f.input :estimated_delivery, in: 0..15, input_html: { min: '0', max: '15' }%>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Salvar', class:'btn btn-primary mt-2' %>
<% end %>

 <%# redirect_to my_profile_path %>

app/views/products/edit.html.erb
<h1>Editar Produto</h1>
<%= render "form", product: @product %>

app/views/products/index.html.erb
<%= render 'shared/bootstrap_container' do%>
    <div class="col-12">
      <% if params[:query] %>
        <p>Você buscou por<strong> "<%= params[:query] %>" </strong>. Encontramos <%= @products.count %> produtos no nosso site.</p>
      <% else %>
        <p>Todos nossos <%= Product.count %> produtos.</p>
      <% end %>
    </div>


  <% @products.each do |product| %>
    <div class="col-md-6 col-xl-4 my-3">
      <div class="card">
        <h5 class="card-header"><%=product.name%></h5>
        <% if product.photo.key %>
          <%= cl_image_tag product.photo.key, class: 'card-img-top card-image', crop: "fill" %>
        <% else %>
          <%= image_tag "blank" %>
        <% end %>
        <div class="card-body">
          <p class="card-text card-description"><%=product.description%></p>
          <div class="row justify-content-between align-items-center">
            <div class="col-5 align-self-center">
              <span class="align-self-center fs-5">R$<%= '%.2f' % product.price%></span>
            </div>
            <div class="col-7 text-end align-items-center">
              <span class="<%='text-primary' if product.estimated_delivery == 0 %>">
                <%if product.estimated_delivery == 0%>
                  Pronta entrega
                <% elsif product.estimated_delivery == 1%>
                  Entrega amanhã
                <% else %>
                  Entrega em <%= product.estimated_delivery %> dias
                <% end %>
              </span>
            </div>
            <div class="col-12 text-end align-items-center">
              Distância: <%= current_user.distance_to(product.user).round(0)%> km
            </div>
            <div class="col-12 mt-2 text-center">
              <%= link_to product_path(product) do %>
                <button class="btn btn-primary w-100 fs-5" >Mais detalhes</button>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/products/new.html.erb
<h1>Cadastrar Novo Produto</h1>
<p>Find me in app/views/products/new.html.erb</p>

<%= render "form", product: @product %>

<%= link_to 'Voltar', profiles_path %>

app/views/products/show.html.erb
<div class="container">
  <div class="row bg-light justify-content-center p-3 border border-grey">
    <div class="col-12 text-center">
      <h4><%= @product.name %></h5>
    </div>
    <div class="col-12 text-center">
      <h5><%= link_to @product.user.name, "../profile/#{@product.user.id}" %></h5>
    </div>
    <div class="row mt-3">
      </div class="col-8 justify-content-center">
        <p><%= @product.description %></p>
        <p>Valor: <b><%= number_to_currency(@product.price, delimiter: "", unit: "R$") %></b></p>
        <p>Entrega em: <b><%= (Date.today + @product.estimated_delivery).strftime("%e, %b %Y") %></b></p>

        <div class="col-6 align-self-center">
          <%= link_to 'Voltar', :back, class:'fs-5' %>
        </div>
        <div class="col-6 text-end">
          <span class='btn btn-primary fs-5' data-bs-toggle="modal" data-bs-target="#exampleModal">Encomendar</span>
        </div>
      <div>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog rounded">
    <div class="modal-content bg-light">
      <div class="modal-header">
        <h4 class="modal-title">Confirmação de pedido</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
        <div class="modal-body">
          <%= render 'orders/new', product: @product%>
        </div>
    </div>
  </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editar Usuario</h1>
<%= simple_form_for(@user, url: profiles_path) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :photo, as: :file %>
  <%= f.submit 'Salvar', class:'btn btn-primary mt-2' %>
<% end %>

app/views/profiles/show.html.erb
<%= render 'shared/bootstrap_container' do%>
  <div class="row">
    <div class="col-1 me-4 me-md-1">
      <% if current_user.photo.key %>
      <%= cl_image_tag current_user.photo.key, class: "avatar-large" %>
      <% else %>
      <%= image_tag "blank-profile-picture", class: "avatar-large" %>
      <% end %>
    </div>
    <div class="col-10">
      <div class="card-profile">
        <div class="card-profile-infos">
          <h3><%= current_user.name %></h3>
          <p><%= current_user.email %></p>
          <p class="<%= current_user.available ? 'text-primary' : 'text-danger'%>" >
            <%= current_user.available ? 'Aberto' : 'Fechado' %>
            <%= simple_form_for(current_user, url: profiles_path) do |f| %>
              <%= f.input :available, as: :hidden, input_html: {value: !current_user.available} %>
              <%= f.submit 'Alterar Disponibilidade', class:'btn btn-primary mt-2' %>
            <% end %>
          </p>
          <%= link_to edit_profiles_path do %>
          <i class="far fa-edit fs-4"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <h3 class='text-center pt-4 my-2'>Seu cardápio</h3>
  <%= link_to 'Cadastrar Novo Produto', new_product_path %>
  <% current_user.products.each do |product| %>
    <div class="card my-3 align-items-stretch">
      <div class="card-header row align-items-center">
        <div class="col-10 align-self-center fs-4">
          <%= product.name %>
        </div>
        <div class="col-2 text-end">
          <%= link_to edit_product_path(product) do %>
          <i class="far fa-edit fs-4"></i>
          <% end %>
          <%= link_to product_path(product), method: :delete do %>
            <i class="fas fa-trash-alt text-danger fs-4"></i>
          <% end %>
        </div>
      </div>
      <div class="m-3">
        <h5 class="card-title">
          Valor: R$<%= product.price %>
        </h5>
        <h5 class="card-title">
          Tempo de produção: <%= pluralize('dia' , product.estimated_delivery) %>
        </h5>
        <p class='card-text'><%= product.description %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/shared/_bootstrap_container.html.erb
<div class="container">
  <div class="row p-2 justify-content-center">
    <%= yield %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "favpng_bakery-icon.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse w-100" id="navbarSupportedContent">
      <ul class="navbar-nav w-100 d-flex justify-content-between">
        <% if user_signed_in? %>
          <div class="d-flex flex-row">
            <li class="nav-item active">
              <%= link_to "Home", root_path, class: "nav-link" %>
            </li><li class="nav-item active">
              <%= link_to "Bolos", products_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Cupcakes", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
              <% link_to "Macarons", "#", class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Docinhos", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Sobremesas", root_path, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "Tortas", root_path, class: "nav-link margem-links"  %>
            </li>
          </div>
          <div>
            <li class="nav-item dropdown">
              <% if current_user.photo.key %>
                <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } %>
              <% else %>
                <%= image_tag "blank-profile-picture", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" } %>
              <% end %>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Meu Perfil", profiles_path, class: "dropdown-item" %>
                <%= link_to "Meus Pedidos", orders_path, class: "dropdown-item" %>
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          </div>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          <% end %>
      </ul>
    </div>
  </div>
</div>